//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-10/27/2009 06:09 PM(mockbuild)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.23 at 06:27:19 PM PST 
//


package com.googlecode.sardine.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{DAV:}creationdate" minOccurs="0"/>
 *         &lt;element ref="{DAV:}displayname" minOccurs="0"/>
 *         &lt;element ref="{DAV:}getcontentlanguage" minOccurs="0"/>
 *         &lt;element ref="{DAV:}getcontentlength" minOccurs="0"/>
 *         &lt;element ref="{DAV:}getcontenttype" minOccurs="0"/>
 *         &lt;element ref="{DAV:}getetag" minOccurs="0"/>
 *         &lt;element ref="{DAV:}getlastmodified" minOccurs="0"/>
 *         &lt;element ref="{DAV:}lockdiscovery" minOccurs="0"/>
 *         &lt;element ref="{DAV:}resourcetype" minOccurs="0"/>
 *         &lt;element ref="{DAV:}supportedlock" minOccurs="0"/>
 *         &lt;element ref="{DAV:}owner" minOccurs="0"/>  &lt;!-- (for DAV:acl) -->
 *         &lt;any/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "property")
public class Property {


	@XmlAnyElement
	private Element property;

	public Element getProperty() {
		return property;
	}

	public void setProperty(Element property) {
		this.property = property;
	}

}
