//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.09.04 at 05:26:16 PM PDT
//


package com.github.sardine.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{DAV:}sync-token"/&gt;
 *         &lt;element ref="{DAV:}sync-level"/&gt;
 *         &lt;element ref="{DAV:}prop"/&gt;
 *         &lt;element ref="{DAV:}limit" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "syncToken",
    "syncLevel",
    "prop",
    "limit"
})
@XmlRootElement(name = "sync-collection")
public class SyncCollection
{

    @XmlElement(name = "sync-token", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String syncToken;
    @XmlElement(name = "sync-level", required = true)
    protected String syncLevel;
    @XmlElement(required = true)
    protected Prop prop;
    protected BigInteger limit;

    /**
     * Gets the value of the syncToken property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSyncToken() {
        return syncToken;
    }

    /**
     * Sets the value of the syncToken property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSyncToken(String value) {
        this.syncToken = value;
    }

    /**
     * Gets the value of the syncLevel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSyncLevel() {
        return syncLevel;
    }

    /**
     * Sets the value of the syncLevel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSyncLevel(String value) {
        this.syncLevel = value;
    }

    /**
     * Gets the value of the prop property.
     *
     * @return
     *     possible object is
     *     {@link Prop }
     *
     */
    public Prop getProp() {
        return prop;
    }

    /**
     * Sets the value of the prop property.
     *
     * @param value
     *     allowed object is
     *     {@link Prop }
     *
     */
    public void setProp(Prop value) {
        this.prop = value;
    }

    /**
     * Gets the value of the limit property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setLimit(BigInteger value) {
        this.limit = value;
    }

}
